spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/springcloudactivity?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      stat-view-servlet:
        login-username: admin
        login-password: admin
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
