spring:
  application:
    name: test
server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@127.0.0.1:8101/eureka/
    fetch-registry: true
    register-with-eureka: true
message:
  value: jiangwandong 123
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
